server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: mini-door-dash-backend
  
  # Database Configuration (Supabase PostgreSQL)
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://db.fbqinbkfgckofqokgevu.supabase.co:5432/postgres?sslmode=require}
    username: ${SUPABASE_DB_USER:postgres}
    password: ${SUPABASE_DB_PASSWORD:3v6-U.sbMnYB@3D}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin

# Supabase Configuration
supabase:
  url: ${SUPABASE_URL:https://your-project.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:your_anon_key}
  service-key: ${SUPABASE_SERVICE_KEY:your_service_key}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here_make_it_long_and_secure}
  expiration: 86400000 # 24 hours in milliseconds

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Logging
logging:
  level:
    com.minidoordash: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 